apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-agent-api
  namespace: multi-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-agent-api
  template:
    metadata:
      labels:
        app: multi-agent-api
    spec:
      containers:
        - name: api
          image: satish27072002/multi-agent-sdlc-api:66181247a8b6
          ports:
            - containerPort: 8080
          env:
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: multi-agent-secrets
                  key: GROQ_API_KEY
            - name: REDIS_URL
              value: redis://redis:6379
---
apiVersion: v1
kind: Service
metadata:
  name: multi-agent-api
  namespace: multi-agent
spec:
  selector:
    app: multi-agent-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
